### ISSUE TITLE
error on launch

### ISSUE THREAD

**Issue by levarar** [Beatso/Schubert#3]
PS C:\Users\Root\Desktop\Schubert-main> npm start

schubert@1.0.0 start C:\Users\Root\Desktop\Schubert-main
> node index.js

bot running
(node:1856) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\Root\Desktop\Schubert-main\node_modules\node-fetch\lib\index.js:1305:9)
    at C:\Users\Root\Desktop\Schubert-main\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\Root\Desktop\Schubert-main\node_modules\node-fetch\lib\index.js:1407:9)
    at Client.set (C:\Users\Root\Desktop\Schubert-main\node_modules\@replit\database\index.js:57:11)
    at Client.<anonymous> (C:\Users\Root\Desktop\Schubert-main\index.js:77:14)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\Root\Desktop\Schubert-main\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Root\Desktop\Schubert-main\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Root\Desktop\Schubert-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1856) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\Root\Desktop\Schubert-main\node_modules\node-fetch\lib\index.js:1305:9)
    at C:\Users\Root\Desktop\Schubert-main\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\Root\Desktop\Schubert-main\node_modules\node-fetch\lib\index.js:1407:9)
    at Client.list (C:\Users\Root\Desktop\Schubert-main\node_modules\@replit\database\index.js:79:18)
    at Client.<anonymous> (C:\Users\Root\Desktop\Schubert-main\index.js:113:11)
    at Client.emit (events.js:315:20)
    at VoiceStateUpdate.handle (C:\Users\Root\Desktop\Schubert-main\node_modules\discord.js\src\client\actions\VoiceStateUpdate.js:40:14)
    at Object.module.exports [as VOICE_STATE_UPDATE] (C:\Users\Root\Desktop\Schubert-main\node_modules\discord.js\src\client\websocket\handlers\VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (C:\Users\Root\Desktop\Schubert-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
(node:1856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

After installing the role and when entering the voice channel, the bot gives an error

**Comment by Beatso** [comment]
i think this is because the code uses the node module @replit/database, which only works properly if it's being hosted with <https://repl.it/>. to host it elsewhere, it would need to be rewritten to use a different database (something like quick.db would work) to store the channels and roles. anyways, schubert is badly written and i plan to rewrite it some time. if you're looking for a ready hosted bot that does the same thing, i recommend <https://top.gg/bot/722403661447430216>
